name: stm-challenge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - dateparser
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - statsmodels
  - xgboost
  - shap
  - jupyterlab
  - ipykernel
  - pip

